-- MySQL Script generated by MySQL Workbench
-- Mon Jul 13 22:14:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital` DEFAULT CHARACTER SET latin1 ;
USE `hospital` ;

-- -----------------------------------------------------
-- Table `hospital`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`Department` ;

CREATE TABLE IF NOT EXISTS `hospital`.`Department` (
  `Dept_Name` VARCHAR(20) NULL,
  `DeptId` INT NOT NULL,
  `deptHead_SSN` INT(9) NULL,
  PRIMARY KEY (`DeptId`),
  INDEX `DeptHead_SSN_idx` (`deptHead_SSN` ASC),
  CONSTRAINT `DeptHead_SSN`
    FOREIGN KEY (`deptHead_SSN`)
    REFERENCES `hospital`.`Employee` (`ssn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`Employee` ;

CREATE TABLE IF NOT EXISTS `hospital`.`Employee` (
  `Fname` VARCHAR(45) NULL,
  `Lname` VARCHAR(45) NULL,
  `ssn` INT(9) NOT NULL,
  `employeeID` INT NULL,
  `Position` VARCHAR(45) NULL,
  `PhoneNumber` VARCHAR(20) NULL,
  `deptID` INT NULL,
  PRIMARY KEY (`ssn`),
  UNIQUE INDEX `PhoneNumber_UNIQUE` (`PhoneNumber` ASC),
  INDEX `deptID_idx` (`deptID` ASC),
  UNIQUE INDEX `employeeID_UNIQUE` (`employeeID` ASC),
  CONSTRAINT `deptID`
    FOREIGN KEY (`deptID`)
    REFERENCES `hospital`.`Department` (`DeptId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Guardian`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`Guardian` ;

CREATE TABLE IF NOT EXISTS `hospital`.`Guardian` (
  `Fname` VARCHAR(20) NULL,
  `Lname` VARCHAR(20) NULL,
  `guardianPhone` VARCHAR(20) NOT NULL,
  `patient_ssn` INT(9) NULL,
  PRIMARY KEY (`guardian_phone`),
  INDEX `patient_ssn_idx` (`patient_ssn` ASC),
  CONSTRAINT `patient_ssn`
    FOREIGN KEY (`patient_ssn`)
    REFERENCES `hospital`.`Patient` (`ssn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`Patient` ;

CREATE TABLE IF NOT EXISTS `hospital`.`Patient` (
  `P_Fname` VARCHAR(20) NULL,
  `P_Lname` VARCHAR(20) NULL,
  `dob` DATE NULL,
  `P_ssn` INT(9) NOT NULL,
  `patientNo` INT NOT NULL,
  `address` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(20) NULL,
  `guardian_Phone` VARCHAR(20) NULL,
  `doctor_inchargeSSN` INT(9) NULL,
  PRIMARY KEY (`ssn`, `patientNo`),
  UNIQUE INDEX `phoneNumber_UNIQUE` (`phoneNumber` ASC),
  INDEX `guardian_Phone_idx` (`guardian_Phone` ASC),
  INDEX `doctor_inchargeSSN_idx` (`doctor_inchargeSSN` ASC),
  CONSTRAINT `guardian_Phone`
    FOREIGN KEY (`guardian_Phone`)
    REFERENCES `hospital`.`Guardian` (`guardian_phone`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `doctor_inchargeSSN`
    FOREIGN KEY (`doctor_inchargeSSN`)
    REFERENCES `hospital`.`Employee` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
